apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe645-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swe645
  template:
    metadata:
      labels:
        app: swe645
    spec:
      containers:
      - name: swe645
        image: surya100599/swe645-survey:v1
        ports:
        - containerPort: 80